# Coverage Badge Configuration (#440)
#
# ProFish uses Codecov for coverage tracking and badge generation.
# Badge URL: https://codecov.io/gh/coredevelopment37-tech/ProFish/branch/main/graph/badge.svg
#
# Configuration for Codecov thresholds:

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 60%
        threshold: 10%

comment:
  layout: 'reach,diff,flags,files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

flags:
  unit:
    paths:
      - src/services/
      - src/config/
    carryforward: true

  integration:
    paths:
      - src/__integration__/
    carryforward: true

ignore:
  - 'node_modules/**'
  - 'android/**'
  - 'ios/**'
  - 'e2e/**'
  - '__mocks__/**'
  - '*.config.js'
