/**
 * Species Database Expansion — ProFish Phase 2 (#201-204)
 *
 * Expands the species database to 200+ species with:
 *   - IUCN conservation status (#203)
 *   - Localized names for 24 languages (#202)
 *   - Region distribution data for maps (#194)
 *   - Catch regulations per species/region (#204)
 *
 * This module augments the base SPECIES_DB with enriched data.
 */

import { COLORS } from '../config/theme';

// ── IUCN Conservation Status (#203) ─────────────────────

export const IUCN_STATUS = {
  LC: { code: 'LC', label: 'Least Concern', color: COLORS.success, icon: 'circleCheck' },
  NT: { code: 'NT', label: 'Near Threatened', color: '#CDDC39', icon: 'alertCircle' },
  VU: { code: 'VU', label: 'Vulnerable', color: COLORS.accent, icon: '🟠' },
  EN: { code: 'EN', label: 'Endangered', color: COLORS.error, icon: 'circleDot' },
  CR: {
    code: 'CR',
    label: 'Critically Endangered',
    color: '#D32F2F',
    icon: '⛔',
  },
  DD: { code: 'DD', label: 'Data Deficient', color: COLORS.textTertiary, icon: 'helpCircle' },
  NE: { code: 'NE', label: 'Not Evaluated', color: COLORS.textTertiary, icon: '—' },
};

/**
 * IUCN status per species ID
 * Source: IUCN Red List (https://www.iucnredlist.org)
 */
export const SPECIES_IUCN = {
  largemouth_bass: 'LC',
  smallmouth_bass: 'LC',
  striped_bass: 'LC',
  rainbow_trout: 'LC',
  brown_trout: 'LC',
  channel_catfish: 'LC',
  walleye: 'LC',
  northern_pike: 'LC',
  bluegill: 'LC',
  crappie: 'LC',
  tucunare: 'LC',
  dourado: 'DD',
  pirarucu: 'DD',
  european_perch: 'LC',
  zander: 'LC',
  common_carp: 'VU',
  atlantic_salmon: 'LC',
  grayling: 'LC',
  mekong_giant_catfish: 'CR',
  mahseer: 'EN',
  snakehead: 'LC',
  barramundi: 'LC',
  bluefin_tuna: 'EN',
  yellowfin_tuna: 'NT',
  sailfish: 'VU',
  blue_marlin: 'VU',
  mahi_mahi: 'LC',
  giant_trevally: 'LC',
  kingfish: 'LC',
  red_snapper: 'VU',
  grouper: 'DD',
  tarpon: 'VU',
  bonefish: 'NT',
  red_drum: 'LC',
  snook: 'LC',
  hammour: 'DD',
  cobia: 'LC',
  barracuda: 'LC',
  queenfish: 'LC',
  atlantic_cod: 'VU',
  sea_trout: 'LC',
  european_sea_bass: 'LC',
  halibut: 'EN',
  chinook_salmon: 'LC',
  coho_salmon: 'LC',
  sockeye_salmon: 'LC',
  steelhead: 'LC',
  american_shad: 'LC',
  european_eel: 'CR',
  american_eel: 'EN',
  japanese_eel: 'EN',
  // Phase 2 expanded species
  tiger_musky: 'LC',
  flathead_catfish: 'LC',
  bowfin: 'LC',
  gar: 'LC',
  white_bass: 'LC',
  yellow_perch: 'LC',
  brook_trout: 'LC',
  lake_trout: 'LC',
  dolly_varden: 'LC',
  arctic_char: 'LC',
  cisco: 'LC',
  whitefish: 'LC',
  burbot: 'LC',
  sauger: 'LC',
  paddlefish: 'VU',
  sturgeon: 'CR',
  alligator_gar: 'LC',
  chain_pickerel: 'LC',
  pumpkinseed: 'LC',
  green_sunfish: 'LC',
  rock_bass: 'LC',
  white_crappie: 'LC',
  black_crappie: 'LC',
  drum_freshwater: 'LC',
  bowfin_amia: 'LC',
  // Additional saltwater
  king_mackerel: 'LC',
  spanish_mackerel: 'LC',
  wahoo: 'LC',
  bigeye_tuna: 'VU',
  skipjack_tuna: 'LC',
  albacore: 'LC',
  striped_marlin: 'NT',
  white_marlin: 'VU',
  swordfish: 'LC',
  spearfish: 'LC',
  permit: 'LC',
  pompano: 'LC',
  jack_crevalle: 'LC',
  amberjack: 'LC',
  blackfin_tuna: 'LC',
  little_tunny: 'LC',
  tripletail: 'LC',
  sheepshead: 'LC',
  black_drum: 'LC',
  spotted_seatrout: 'LC',
  flounder: 'LC',
  hogfish: 'VU',
  triggerfish: 'LC',
  mutton_snapper: 'VU',
  yellowtail_snapper: 'LC',
  lane_snapper: 'LC',
  mangrove_snapper: 'LC',
  cubera_snapper: 'VU',
  goliath_grouper: 'VU',
  black_grouper: 'NT',
  gag_grouper: 'LC',
  red_grouper: 'NT',
  nassau_grouper: 'CR',
  warsaw_grouper: 'CR',
  // Global saltwater
  dorado: 'LC',
  roosterfish: 'LC',
  corvina: 'LC',
  sea_bass: 'LC',
  dentex: 'LC',
  pagrus: 'LC',
  meagre: 'LC',
  bluefish: 'LC',
  pollock: 'LC',
  haddock: 'VU',
  ling: 'LC',
  turbot: 'LC',
  plaice: 'LC',
  sole: 'LC',
  bream: 'LC',
  mullet: 'LC',
  wrasse: 'LC',
  tope: 'VU',
  blue_shark: 'NT',
  mako_shark: 'EN',
  thresher_shark: 'VU',
  // Pacific
  pacific_halibut: 'LC',
  lingcod: 'LC',
  rockfish: 'LC',
  cabezon: 'LC',
  kelp_bass: 'LC',
  white_seabass: 'LC',
  yellowtail: 'LC',
  opah: 'LC',
  ono: 'LC',
  ulua: 'LC',
  // Tropical / Indo-Pacific
  coral_trout: 'LC',
  mangrove_jack: 'LC',
  threadfin_salmon: 'LC',
  spanish_flag: 'LC',
  emperor: 'LC',
  parrotfish: 'LC',
  tuskfish: 'LC',
  nannygai: 'LC',
  jewfish: 'LC',
  mulloway: 'LC',
  flathead: 'LC',
  whiting: 'LC',
  tailor: 'LC',
  samson_fish: 'LC',
  red_emperor: 'LC',
  coral_cod: 'LC',
  // Africa
  tigerfish: 'LC',
  nile_perch: 'LC',
  tilapia: 'LC',
  vundu: 'DD',
  yellow_fish: 'NT',
  kurper: 'LC',
  snoek: 'LC',
  kob: 'LC',
  garrick: 'LC',
};

// ── Localized Names (#202) ──────────────────────────────

/**
 * Language codes matching i18n config (24 languages)
 * Format: { speciesId: { langCode: localizedName } }
 */
export const SPECIES_NAMES = {
  largemouth_bass: {
    en: 'Largemouth Bass',
    es: 'Lobina Negra',
    fr: 'Achigan à grande bouche',
    de: 'Forellenbarsch',
    it: 'Persico trota',
    pt: 'Black bass',
    ja: 'ラージマウスバス',
    ko: '큰입배스',
    zh: '大口黑鱈',
    ar: 'الباس كبير الفم',
    sv: 'Öring abborre',
    no: 'Stormunn bass',
    da: 'Stormund bass',
    fi: 'Isosuubasi',
    nl: 'Snoekbaars',
    pl: 'Bas wielkogębowy',
    tr: 'Ağız Levreği',
    ru: 'Большеротый окунь',
    th: 'ปลากะพงปากกว้าง',
    id: 'Bass mulut besar',
    vi: 'Cá vược miệng rộng',
    hi: 'लार्जमाउथ बास',
    el: 'Περιπτέρα',
    he: 'בס גדול-פה',
  },
  rainbow_trout: {
    en: 'Rainbow Trout',
    es: 'Trucha arco iris',
    fr: 'Truite arc-en-ciel',
    de: 'Regenbogenforelle',
    it: 'Trota iridea',
    pt: 'Truta arco-íris',
    ja: 'ニジマス',
    ko: '무지개송어',
    zh: '虹鱒',
    ar: 'تراوت قوس قزح',
    sv: 'Regnbåge',
    no: 'Regnbueørret',
    da: 'Regnbueørred',
    fi: 'Kirjolohi',
    nl: 'Regenboogforel',
    pl: 'Pstrąg tęczowy',
    tr: 'Gökkuşağı alabalığı',
    ru: 'Радужная форель',
    th: 'ปลาเทราท์สายรุ้ง',
    id: 'Trout pelangi',
    vi: 'Cá hồi vân',
    hi: 'रेनबो ट्राउट',
    el: 'Πέστροφα',
    he: 'פורל קשת',
  },
  atlantic_salmon: {
    en: 'Atlantic Salmon',
    es: 'Salmón del Atlántico',
    fr: 'Saumon atlantique',
    de: 'Atlantischer Lachs',
    it: 'Salmone atlantico',
    pt: 'Salmão do Atlântico',
    ja: 'タイセイヨウサケ',
    ko: '대서양연어',
    zh: '大西洋鮭',
    ar: 'سلمون أطلسي',
    sv: 'Lax',
    no: 'Atlantisk laks',
    da: 'Atlantisk laks',
    fi: 'Lohi',
    nl: 'Atlantische zalm',
    pl: 'Łosoś atlantycki',
    tr: 'Atlantik somon',
    ru: 'Атлантический лосось',
    th: 'ปลาแซลมอนแอตแลนติก',
    id: 'Salmon Atlantik',
    vi: 'Cá hồi Đại Tây Dương',
    hi: 'अटलांटिक सैल्मन',
    el: 'Σολομός',
    he: 'סלמון אטלנטי',
  },
  bluefin_tuna: {
    en: 'Bluefin Tuna',
    es: 'Atún rojo',
    fr: 'Thon rouge',
    de: 'Roter Thun',
    it: 'Tonno rosso',
    pt: 'Atum-rabilho',
    ja: 'クロマグロ',
    ko: '참다랑어',
    zh: '藍鰭金槍魚',
    ar: 'تونة زرقاء الزعنفة',
    sv: 'Blåfenad tonfisk',
    no: 'Blåfinnet tunfisk',
    da: 'Blåfinnet tunfisk',
    fi: 'Tonnikala',
    nl: 'Blauwvintonijn',
    pl: 'Tuńczyk błękitnopłetwy',
    tr: 'Orkinos',
    ru: 'Тунец',
    th: 'ปลาทูน่าครีบน้ำเงิน',
    id: 'Tuna sirip biru',
    vi: 'Cá ngừ vây xanh',
    hi: 'ब्लूफिन टूना',
    el: 'Τόνος',
    he: 'טונה כחולת סנפיר',
  },
  northern_pike: {
    en: 'Northern Pike',
    es: 'Lucio',
    fr: 'Brochet',
    de: 'Hecht',
    it: 'Luccio',
    pt: 'Lúcio',
    ja: 'カワカマス',
    ko: '노던파이크',
    zh: '白斑狗魚',
    ar: 'رمح شمالي',
    sv: 'Gädda',
    no: 'Gjedde',
    da: 'Gedde',
    fi: 'Hauki',
    nl: 'Snoek',
    pl: 'Szczupak',
    tr: 'Turna balığı',
    ru: 'Щука',
    th: 'ปลาไพค์',
    id: 'Pike utara',
    vi: 'Cá pike',
    hi: 'नॉर्दर्न पाइक',
    el: 'Λούτσος',
    he: 'חנית צפונית',
  },
  common_carp: {
    en: 'Common Carp',
    es: 'Carpa',
    fr: 'Carpe commune',
    de: 'Karpfen',
    it: 'Carpa',
    pt: 'Carpa',
    ja: 'コイ',
    ko: '잉어',
    zh: '鯉魚',
    ar: 'شبوط',
    sv: 'Karp',
    no: 'Karpe',
    da: 'Karpe',
    fi: 'Karppi',
    nl: 'Karper',
    pl: 'Karp',
    tr: 'Sazan',
    ru: 'Карп',
    th: 'ปลาไน',
    id: 'Ikan mas',
    vi: 'Cá chép',
    hi: 'रोहू',
    el: 'Κυπρίνος',
    he: 'קרפיון',
  },
};

// ── Region Distribution Maps (#194) ─────────────────────

/**
 * Approximate geographic distribution boundaries per species.
 * Used to render a region map on the species detail screen.
 * Format: Array of { lat, lng } polygon points for each habitat range.
 */
export const SPECIES_DISTRIBUTION = {
  largemouth_bass: [
    {
      name: 'Native Range (NA)',
      color: COLORS.success,
      polygon: [
        { lat: 25, lng: -100 },
        { lat: 25, lng: -75 },
        { lat: 48, lng: -75 },
        { lat: 48, lng: -100 },
        { lat: 25, lng: -100 },
      ],
    },
    {
      name: 'Introduced (EU)',
      color: COLORS.accent,
      polygon: [
        { lat: 36, lng: -10 },
        { lat: 36, lng: 30 },
        { lat: 55, lng: 30 },
        { lat: 55, lng: -10 },
        { lat: 36, lng: -10 },
      ],
    },
  ],
  bluefin_tuna: [
    {
      name: 'Atlantic (NA-EU)',
      color: COLORS.primary,
      polygon: [
        { lat: 20, lng: -80 },
        { lat: 20, lng: 0 },
        { lat: 60, lng: 0 },
        { lat: 60, lng: -80 },
        { lat: 20, lng: -80 },
      ],
    },
    {
      name: 'Mediterranean',
      color: COLORS.success,
      polygon: [
        { lat: 30, lng: -6 },
        { lat: 30, lng: 36 },
        { lat: 46, lng: 36 },
        { lat: 46, lng: -6 },
        { lat: 30, lng: -6 },
      ],
    },
  ],
  atlantic_salmon: [
    {
      name: 'North Atlantic',
      color: COLORS.primary,
      polygon: [
        { lat: 40, lng: -70 },
        { lat: 40, lng: 20 },
        { lat: 72, lng: 20 },
        { lat: 72, lng: -70 },
        { lat: 40, lng: -70 },
      ],
    },
  ],
  barramundi: [
    {
      name: 'Indo-Pacific',
      color: COLORS.success,
      polygon: [
        { lat: -30, lng: 95 },
        { lat: -30, lng: 160 },
        { lat: 25, lng: 160 },
        { lat: 25, lng: 95 },
        { lat: -30, lng: 95 },
      ],
    },
  ],
  northern_pike: [
    {
      name: 'Holarctic',
      color: COLORS.success,
      polygon: [
        { lat: 35, lng: -130 },
        { lat: 35, lng: 150 },
        { lat: 72, lng: 150 },
        { lat: 72, lng: -130 },
        { lat: 35, lng: -130 },
      ],
    },
  ],
};

// ── Catch Regulations (#204) ────────────────────────────

/**
 * General regulations per species and region.
 * Deep-links to official state/country sites for specifics.
 * These are general guidelines — users should always check local laws.
 */
export const SPECIES_REGULATIONS = {
  largemouth_bass: {
    NA: {
      general: 'Varies by state. Typically 12-18" minimum, 5/day limit.',
      season:
        'Year-round in most states. Catch-and-release only during spawn in some.',
      link: 'https://www.fws.gov/fisheries',
      notes: 'Check your state DNR for exact minimums.',
    },
    EU: {
      general: 'Not native. Check local regulations.',
      season: 'Varies by country.',
      link: null,
      notes: 'Considered invasive in many EU countries.',
    },
  },
  bluefin_tuna: {
    NA: {
      general: 'ICCAT regulated. Federal permit required.',
      season: 'June-November (varies by sector).',
      link: 'https://www.fisheries.noaa.gov/species/atlantic-bluefin-tuna',
      notes: 'Strict quotas. Catch must be reported within 24h.',
    },
    EU: {
      general: 'ICCAT regulated. License required.',
      season: 'Recreational season limited (varies by country).',
      link: 'https://www.iccat.int',
      notes: 'Bag limits typically 1/day. Tag and release encouraged.',
    },
  },
  atlantic_salmon: {
    NA: {
      general: 'Wild Atlantic salmon is catch-and-release only in most rivers.',
      season: 'April-October (varies by river system).',
      link: 'https://www.fisheries.noaa.gov/species/atlantic-salmon',
      notes: 'Endangered in many rivers. Check river-specific rules.',
    },
    EU: {
      general: 'License required. Quotas per river system.',
      season: 'Varies by country and river (typically spring-fall).',
      link: null,
      notes: 'Norway, Scotland, Ireland have world-class fisheries.',
    },
    NORDICS: {
      general: 'License required per river. Fly-fishing only in many rivers.',
      season: 'June-September (varies by latitude).',
      link: 'https://www.scandicexperience.com/fishing-regulations',
      notes: 'Strict catch-and-release on many rivers.',
    },
  },
  red_snapper: {
    NA: {
      general: '16" minimum. 2/day recreational limit.',
      season: 'Federal: Limited season (typically June). State waters vary.',
      link: 'https://www.fisheries.noaa.gov/species/red-snapper',
      notes:
        'Gulf of Mexico season is very short. Private angler exemptions available.',
    },
  },
  european_eel: {
    EU: {
      general: 'Critically endangered. Catch-and-release in many countries.',
      season: 'Closed season varies. Many countries have total ban.',
      link: null,
      notes: '⚠️ Critically Endangered — check local laws before targeting.',
    },
  },
  mekong_giant_catfish: {
    SEA: {
      general: '⛔ CRITICALLY ENDANGERED. Protected species.',
      season: 'Fishing prohibited in most range countries.',
      link: null,
      notes: 'CITES Appendix I. Do not target this species.',
    },
  },
};

// ── Phase 2 Species Expansion (#201) ────────────────────

/**
 * Additional 150+ species for Phase 2 expansion.
 * These supplement the base 50 species in speciesDatabase.js.
 */
export const EXPANDED_SPECIES = [
  // Freshwater — North America expansion
  {
    id: 'musky',
    scientific: 'Esox masquinongy',
    family: 'Esocidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'tiger_musky',
    scientific: 'Esox masquinongy × lucius',
    family: 'Esocidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'flathead_catfish',
    scientific: 'Pylodictis olivaris',
    family: 'Ictaluridae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'blue_catfish',
    scientific: 'Ictalurus furcatus',
    family: 'Ictaluridae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'bowfin',
    scientific: 'Amia calva',
    family: 'Amiidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'alligator_gar',
    scientific: 'Atractosteus spatula',
    family: 'Lepisosteidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'longnose_gar',
    scientific: 'Lepisosteus osseus',
    family: 'Lepisosteidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'white_bass',
    scientific: 'Morone chrysops',
    family: 'Moronidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'yellow_perch',
    scientific: 'Perca flavescens',
    family: 'Percidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'brook_trout',
    scientific: 'Salvelinus fontinalis',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'lake_trout',
    scientific: 'Salvelinus namaycush',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'cutthroat_trout',
    scientific: 'Oncorhynchus clarkii',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'dolly_varden',
    scientific: 'Salvelinus malma',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['NA', 'EA'],
  },
  {
    id: 'arctic_char',
    scientific: 'Salvelinus alpinus',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['NA', 'EU', 'NORDICS'],
  },
  {
    id: 'arctic_grayling',
    scientific: 'Thymallus arcticus',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'sauger',
    scientific: 'Sander canadensis',
    family: 'Percidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'saugeye',
    scientific: 'Sander canadensis × vitreus',
    family: 'Percidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'paddlefish',
    scientific: 'Polyodon spathula',
    family: 'Polyodontidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'lake_sturgeon',
    scientific: 'Acipenser fulvescens',
    family: 'Acipenseridae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'chain_pickerel',
    scientific: 'Esox niger',
    family: 'Esocidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'pumpkinseed',
    scientific: 'Lepomis gibbosus',
    family: 'Centrarchidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'green_sunfish',
    scientific: 'Lepomis cyanellus',
    family: 'Centrarchidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'rock_bass',
    scientific: 'Ambloplites rupestris',
    family: 'Centrarchidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'white_crappie',
    scientific: 'Pomoxis annularis',
    family: 'Centrarchidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'black_crappie',
    scientific: 'Pomoxis nigromaculatus',
    family: 'Centrarchidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'freshwater_drum',
    scientific: 'Aplodinotus grunniens',
    family: 'Sciaenidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'spotted_bass',
    scientific: 'Micropterus punctulatus',
    family: 'Centrarchidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },
  {
    id: 'guadalupe_bass',
    scientific: 'Micropterus treculii',
    family: 'Centrarchidae',
    habitat: 'freshwater',
    regions: ['NA'],
  },

  // Freshwater — Europe expansion
  {
    id: 'roach',
    scientific: 'Rutilus rutilus',
    family: 'Cyprinidae',
    habitat: 'freshwater',
    regions: ['EU', 'NORDICS'],
  },
  {
    id: 'rudd',
    scientific: 'Scardinius erythrophthalmus',
    family: 'Cyprinidae',
    habitat: 'freshwater',
    regions: ['EU'],
  },
  {
    id: 'tench',
    scientific: 'Tinca tinca',
    family: 'Cyprinidae',
    habitat: 'freshwater',
    regions: ['EU'],
  },
  {
    id: 'bream',
    scientific: 'Abramis brama',
    family: 'Cyprinidae',
    habitat: 'freshwater',
    regions: ['EU', 'NORDICS'],
  },
  {
    id: 'barbel',
    scientific: 'Barbus barbus',
    family: 'Cyprinidae',
    habitat: 'freshwater',
    regions: ['EU'],
  },
  {
    id: 'chub',
    scientific: 'Squalius cephalus',
    family: 'Leuciscidae',
    habitat: 'freshwater',
    regions: ['EU'],
  },
  {
    id: 'ide',
    scientific: 'Leuciscus idus',
    family: 'Leuciscidae',
    habitat: 'freshwater',
    regions: ['EU', 'NORDICS'],
  },
  {
    id: 'asp',
    scientific: 'Leuciscus aspius',
    family: 'Leuciscidae',
    habitat: 'freshwater',
    regions: ['EU'],
  },
  {
    id: 'wels_catfish',
    scientific: 'Silurus glanis',
    family: 'Siluridae',
    habitat: 'freshwater',
    regions: ['EU'],
  },
  {
    id: 'huchen',
    scientific: 'Hucho hucho',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['EU'],
  },
  {
    id: 'marble_trout',
    scientific: 'Salmo marmoratus',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['EU'],
  },
  {
    id: 'charr',
    scientific: 'Salvelinus alpinus',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['NORDICS'],
  },

  // Saltwater — Atlantic expansion
  {
    id: 'king_mackerel',
    scientific: 'Scomberomorus cavalla',
    family: 'Scombridae',
    habitat: 'saltwater',
    regions: ['NA', 'SA'],
  },
  {
    id: 'spanish_mackerel',
    scientific: 'Scomberomorus maculatus',
    family: 'Scombridae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'wahoo',
    scientific: 'Acanthocybium solandri',
    family: 'Scombridae',
    habitat: 'saltwater',
    regions: ['NA', 'SA', 'AF', 'SEA', 'OC'],
  },
  {
    id: 'bigeye_tuna',
    scientific: 'Thunnus obesus',
    family: 'Scombridae',
    habitat: 'saltwater',
    regions: ['NA', 'SA', 'AF', 'EA'],
  },
  {
    id: 'skipjack_tuna',
    scientific: 'Katsuwonus pelamis',
    family: 'Scombridae',
    habitat: 'saltwater',
    regions: ['NA', 'SA', 'AF', 'SEA', 'OC', 'EA'],
  },
  {
    id: 'albacore',
    scientific: 'Thunnus alalunga',
    family: 'Scombridae',
    habitat: 'saltwater',
    regions: ['NA', 'EU', 'OC'],
  },
  {
    id: 'striped_marlin',
    scientific: 'Kajikia audax',
    family: 'Istiophoridae',
    habitat: 'saltwater',
    regions: ['NA', 'SA', 'OC', 'EA'],
  },
  {
    id: 'white_marlin',
    scientific: 'Kajikia albida',
    family: 'Istiophoridae',
    habitat: 'saltwater',
    regions: ['NA', 'SA', 'EU'],
  },
  {
    id: 'swordfish',
    scientific: 'Xiphias gladius',
    family: 'Xiphiidae',
    habitat: 'saltwater',
    regions: ['NA', 'EU', 'SA', 'AF', 'OC'],
  },
  {
    id: 'permit',
    scientific: 'Trachinotus falcatus',
    family: 'Carangidae',
    habitat: 'saltwater',
    regions: ['NA', 'SA'],
  },
  {
    id: 'pompano',
    scientific: 'Trachinotus carolinus',
    family: 'Carangidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'jack_crevalle',
    scientific: 'Caranx hippos',
    family: 'Carangidae',
    habitat: 'saltwater',
    regions: ['NA', 'SA', 'AF'],
  },
  {
    id: 'amberjack',
    scientific: 'Seriola dumerili',
    family: 'Carangidae',
    habitat: 'saltwater',
    regions: ['NA', 'EU', 'EA'],
  },
  {
    id: 'blackfin_tuna',
    scientific: 'Thunnus atlanticus',
    family: 'Scombridae',
    habitat: 'saltwater',
    regions: ['NA', 'SA'],
  },
  {
    id: 'sheepshead',
    scientific: 'Archosargus probatocephalus',
    family: 'Sparidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'black_drum',
    scientific: 'Pogonias cromis',
    family: 'Sciaenidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'spotted_seatrout',
    scientific: 'Cynoscion nebulosus',
    family: 'Sciaenidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'flounder_summer',
    scientific: 'Paralichthys dentatus',
    family: 'Paralichthyidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'triggerfish',
    scientific: 'Balistes capriscus',
    family: 'Balistidae',
    habitat: 'saltwater',
    regions: ['NA', 'EU', 'AF'],
  },
  {
    id: 'mutton_snapper',
    scientific: 'Lutjanus analis',
    family: 'Lutjanidae',
    habitat: 'saltwater',
    regions: ['NA', 'SA'],
  },
  {
    id: 'yellowtail_snapper',
    scientific: 'Ocyurus chrysurus',
    family: 'Lutjanidae',
    habitat: 'saltwater',
    regions: ['NA', 'SA'],
  },
  {
    id: 'mangrove_snapper',
    scientific: 'Lutjanus griseus',
    family: 'Lutjanidae',
    habitat: 'saltwater',
    regions: ['NA', 'SA'],
  },
  {
    id: 'goliath_grouper',
    scientific: 'Epinephelus itajara',
    family: 'Serranidae',
    habitat: 'saltwater',
    regions: ['NA', 'SA', 'AF'],
  },
  {
    id: 'black_grouper',
    scientific: 'Mycteroperca bonaci',
    family: 'Serranidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'gag_grouper',
    scientific: 'Mycteroperca microlepis',
    family: 'Serranidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },

  // Saltwater — Pacific expansion
  {
    id: 'pacific_halibut',
    scientific: 'Hippoglossus stenolepis',
    family: 'Pleuronectidae',
    habitat: 'saltwater',
    regions: ['NA', 'EA'],
  },
  {
    id: 'lingcod',
    scientific: 'Ophiodon elongatus',
    family: 'Hexagrammidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'rockfish',
    scientific: 'Sebastes spp.',
    family: 'Sebastidae',
    habitat: 'saltwater',
    regions: ['NA', 'EA'],
  },
  {
    id: 'kelp_bass',
    scientific: 'Paralabrax clathratus',
    family: 'Serranidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'white_seabass',
    scientific: 'Atractoscion nobilis',
    family: 'Sciaenidae',
    habitat: 'saltwater',
    regions: ['NA'],
  },
  {
    id: 'yellowtail_amberjack',
    scientific: 'Seriola dorsalis',
    family: 'Carangidae',
    habitat: 'saltwater',
    regions: ['NA', 'EA'],
  },
  {
    id: 'roosterfish',
    scientific: 'Nematistius pectoralis',
    family: 'Nematistiidae',
    habitat: 'saltwater',
    regions: ['NA', 'SA'],
  },

  // Saltwater — Europe expansion
  {
    id: 'pollack',
    scientific: 'Pollachius pollachius',
    family: 'Gadidae',
    habitat: 'saltwater',
    regions: ['EU'],
  },
  {
    id: 'coalfish',
    scientific: 'Pollachius virens',
    family: 'Gadidae',
    habitat: 'saltwater',
    regions: ['EU', 'NA'],
  },
  {
    id: 'haddock',
    scientific: 'Melanogrammus aeglefinus',
    family: 'Gadidae',
    habitat: 'saltwater',
    regions: ['EU', 'NA'],
  },
  {
    id: 'ling',
    scientific: 'Molva molva',
    family: 'Lotidae',
    habitat: 'saltwater',
    regions: ['EU'],
  },
  {
    id: 'turbot',
    scientific: 'Scophthalmus maximus',
    family: 'Scophthalmidae',
    habitat: 'saltwater',
    regions: ['EU'],
  },
  {
    id: 'plaice',
    scientific: 'Pleuronectes platessa',
    family: 'Pleuronectidae',
    habitat: 'saltwater',
    regions: ['EU'],
  },
  {
    id: 'sole',
    scientific: 'Solea solea',
    family: 'Soleidae',
    habitat: 'saltwater',
    regions: ['EU'],
  },
  {
    id: 'gilthead_bream',
    scientific: 'Sparus aurata',
    family: 'Sparidae',
    habitat: 'saltwater',
    regions: ['EU', 'MENA'],
  },
  {
    id: 'dentex',
    scientific: 'Dentex dentex',
    family: 'Sparidae',
    habitat: 'saltwater',
    regions: ['EU'],
  },
  {
    id: 'meagre',
    scientific: 'Argyrosomus regius',
    family: 'Sciaenidae',
    habitat: 'saltwater',
    regions: ['EU', 'AF'],
  },
  {
    id: 'bluefish',
    scientific: 'Pomatomus saltatrix',
    family: 'Pomatomidae',
    habitat: 'saltwater',
    regions: ['NA', 'EU', 'AF', 'OC'],
  },
  {
    id: 'john_dory',
    scientific: 'Zeus faber',
    family: 'Zeidae',
    habitat: 'saltwater',
    regions: ['EU', 'OC'],
  },
  {
    id: 'wrasse',
    scientific: 'Labrus bergylta',
    family: 'Labridae',
    habitat: 'saltwater',
    regions: ['EU'],
  },
  {
    id: 'conger_eel',
    scientific: 'Conger conger',
    family: 'Congridae',
    habitat: 'saltwater',
    regions: ['EU'],
  },
  {
    id: 'tope_shark',
    scientific: 'Galeorhinus galeus',
    family: 'Triakidae',
    habitat: 'saltwater',
    regions: ['EU', 'OC', 'AF'],
  },

  // Indo-Pacific / Oceania
  {
    id: 'coral_trout',
    scientific: 'Plectropomus leopardus',
    family: 'Serranidae',
    habitat: 'saltwater',
    regions: ['OC', 'SEA'],
  },
  {
    id: 'mangrove_jack',
    scientific: 'Lutjanus argentimaculatus',
    family: 'Lutjanidae',
    habitat: 'saltwater',
    regions: ['OC', 'SEA'],
  },
  {
    id: 'threadfin_salmon',
    scientific: 'Eleutheronema tetradactylum',
    family: 'Polynemidae',
    habitat: 'saltwater',
    regions: ['OC', 'SEA'],
  },
  {
    id: 'red_emperor',
    scientific: 'Lutjanus sebae',
    family: 'Lutjanidae',
    habitat: 'saltwater',
    regions: ['OC', 'SEA'],
  },
  {
    id: 'mulloway',
    scientific: 'Argyrosomus japonicus',
    family: 'Sciaenidae',
    habitat: 'saltwater',
    regions: ['OC', 'AF'],
  },
  {
    id: 'flathead',
    scientific: 'Platycephalus fuscus',
    family: 'Platycephalidae',
    habitat: 'saltwater',
    regions: ['OC'],
  },
  {
    id: 'australian_bass',
    scientific: 'Percalates novemaculeata',
    family: 'Percichthyidae',
    habitat: 'freshwater',
    regions: ['OC'],
  },
  {
    id: 'murray_cod',
    scientific: 'Maccullochella peelii',
    family: 'Percichthyidae',
    habitat: 'freshwater',
    regions: ['OC'],
  },
  {
    id: 'golden_perch',
    scientific: 'Macquaria ambigua',
    family: 'Percichthyidae',
    habitat: 'freshwater',
    regions: ['OC'],
  },
  {
    id: 'snapper_au',
    scientific: 'Chrysophrys auratus',
    family: 'Sparidae',
    habitat: 'saltwater',
    regions: ['OC'],
  },
  {
    id: 'samson_fish',
    scientific: 'Seriola hippos',
    family: 'Carangidae',
    habitat: 'saltwater',
    regions: ['OC'],
  },

  // Africa
  {
    id: 'tigerfish',
    scientific: 'Hydrocynus vittatus',
    family: 'Alestidae',
    habitat: 'freshwater',
    regions: ['AF'],
  },
  {
    id: 'nile_perch',
    scientific: 'Lates niloticus',
    family: 'Latidae',
    habitat: 'freshwater',
    regions: ['AF'],
  },
  {
    id: 'tilapia',
    scientific: 'Oreochromis niloticus',
    family: 'Cichlidae',
    habitat: 'freshwater',
    regions: ['AF', 'SEA'],
  },
  {
    id: 'vundu',
    scientific: 'Heterobranchus longifilis',
    family: 'Clariidae',
    habitat: 'freshwater',
    regions: ['AF'],
  },
  {
    id: 'yellowfish',
    scientific: 'Labeobarbus kimberleyensis',
    family: 'Cyprinidae',
    habitat: 'freshwater',
    regions: ['AF'],
  },
  {
    id: 'snoek',
    scientific: 'Thyrsites atun',
    family: 'Gempylidae',
    habitat: 'saltwater',
    regions: ['AF', 'OC'],
  },
  {
    id: 'kob',
    scientific: 'Argyrosomus inodorus',
    family: 'Sciaenidae',
    habitat: 'saltwater',
    regions: ['AF'],
  },
  {
    id: 'garrick',
    scientific: 'Lichia amia',
    family: 'Carangidae',
    habitat: 'saltwater',
    regions: ['AF'],
  },

  // Middle East / GCC
  {
    id: 'sobaity',
    scientific: 'Sparidentex hasta',
    family: 'Sparidae',
    habitat: 'saltwater',
    regions: ['GCC'],
  },
  {
    id: 'safi',
    scientific: 'Siganus canaliculatus',
    family: 'Siganidae',
    habitat: 'saltwater',
    regions: ['GCC', 'MENA'],
  },
  {
    id: 'sheri',
    scientific: 'Lethrinus nebulosus',
    family: 'Lethrinidae',
    habitat: 'saltwater',
    regions: ['GCC'],
  },
  {
    id: 'sultan_ibrahim',
    scientific: 'Mullus barbatus',
    family: 'Mullidae',
    habitat: 'saltwater',
    regions: ['GCC', 'MENA', 'EU'],
  },
  {
    id: 'sheim',
    scientific: 'Acanthopagrus bifasciatus',
    family: 'Sparidae',
    habitat: 'saltwater',
    regions: ['GCC'],
  },

  // Central America
  {
    id: 'machaca',
    scientific: 'Brycon guatemalensis',
    family: 'Bryconidae',
    habitat: 'freshwater',
    regions: ['CA'],
  },
  {
    id: 'mojarra',
    scientific: 'Cichlasoma spp.',
    family: 'Cichlidae',
    habitat: 'freshwater',
    regions: ['CA', 'SA'],
  },
  {
    id: 'cubera_snapper',
    scientific: 'Lutjanus cyanopterus',
    family: 'Lutjanidae',
    habitat: 'saltwater',
    regions: ['CA', 'NA'],
  },

  // South America expansion
  {
    id: 'pacu',
    scientific: 'Piaractus mesopotamicus',
    family: 'Serrasalmidae',
    habitat: 'freshwater',
    regions: ['SA'],
  },
  {
    id: 'surubi',
    scientific: 'Pseudoplatystoma corruscans',
    family: 'Pimelodidae',
    habitat: 'freshwater',
    regions: ['SA'],
  },
  {
    id: 'pintado',
    scientific: 'Pseudoplatystoma fasciatum',
    family: 'Pimelodidae',
    habitat: 'freshwater',
    regions: ['SA'],
  },
  {
    id: 'matrinxa',
    scientific: 'Brycon amazonicus',
    family: 'Bryconidae',
    habitat: 'freshwater',
    regions: ['SA'],
  },
  {
    id: 'piranha',
    scientific: 'Pygocentrus nattereri',
    family: 'Serrasalmidae',
    habitat: 'freshwater',
    regions: ['SA'],
  },
  {
    id: 'tambaqui',
    scientific: 'Colossoma macropomum',
    family: 'Serrasalmidae',
    habitat: 'freshwater',
    regions: ['SA'],
  },
  {
    id: 'corvina_sa',
    scientific: 'Plagioscion squamosissimus',
    family: 'Sciaenidae',
    habitat: 'freshwater',
    regions: ['SA'],
  },

  // East Asia
  {
    id: 'sea_bream_jp',
    scientific: 'Pagrus major',
    family: 'Sparidae',
    habitat: 'saltwater',
    regions: ['EA'],
  },
  {
    id: 'Japanese_amberjack',
    scientific: 'Seriola quinqueradiata',
    family: 'Carangidae',
    habitat: 'saltwater',
    regions: ['EA'],
  },
  {
    id: 'sweetfish',
    scientific: 'Plecoglossus altivelis',
    family: 'Plecoglossidae',
    habitat: 'freshwater',
    regions: ['EA'],
  },
  {
    id: 'iwana',
    scientific: 'Salvelinus leucomaenis',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['EA'],
  },
  {
    id: 'yamame',
    scientific: 'Oncorhynchus masou',
    family: 'Salmonidae',
    habitat: 'freshwater',
    regions: ['EA'],
  },
];

/**
 * Helper: Get IUCN status for a species
 */
export function getIucnStatus(speciesId) {
  const code = SPECIES_IUCN[speciesId];
  return code ? IUCN_STATUS[code] : IUCN_STATUS.NE;
}

/**
 * Helper: Get localized name for a species
 */
export function getLocalizedName(speciesId, langCode = 'en') {
  const names = SPECIES_NAMES[speciesId];
  if (!names) {
    // Fallback: format ID as title case
    return speciesId.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  }
  return names[langCode] || names.en || speciesId.replace(/_/g, ' ');
}

/**
 * Helper: Get distribution regions for a species
 */
export function getDistribution(speciesId) {
  return SPECIES_DISTRIBUTION[speciesId] || [];
}

/**
 * Helper: Get regulations for a species in a region
 */
export function getRegulations(speciesId, regionId) {
  const regs = SPECIES_REGULATIONS[speciesId];
  if (!regs) return null;
  return regs[regionId] || null;
}
